# -*- coding: utf-8 -*-
"""exercicio 1 esfera balde.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JNKp8gVxkc30fkXd1HTfY9Vm8QaEtDRK

####Nome: Jonatas da Silva Nonato
####Matricula: 202104403216
"""

from math import pi

def balde(r1,r2,h): 


  volume_balde = pi*r1**2*h

  esfera = 4/3*pi*(r2**3)

  print('o volume do balde é {:.0f}m³'.format(volume_balde))
  print('o volume da esfera é {:.0f}m³'.format(esfera))


  if esfera <= volume_balde:
    print('a esfera cabe')
  else:
    print('a esfera não cabe')


balde (20,20,10)

#r1 = float(10) 
#r2 = float(20)
#h = float(2*r1)