# -*- coding: utf-8 -*-
"""exercícios lista parte 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aeysc-WvZJ6ZNm0EtK49K7RRkM5sz4TS

####Jonatas da Silva Nonato 202104403216

###Ler uma lista de 5 números inteiros e mostre cada número juntamente com a sua posição na lista.
"""

q1 = [1,2,3,4,5]

for i, p in enumerate(q1):
  print(i,'=',p)

"""###Ler uma lista de 10 numeros reais e mostre-os na ordem inversa"""

q2 = [1.1,2.5,3.85,5.23,7.83,8.50,9.63,10.23,11.11,13.7]
print(q2)

q2.reverse()

print(q2)

"""###Ler uma lista com 4 notas, em seguida o programa deve exibir as notas e a média"""

q3 = [8.5,6.4,3.8,10]

for med in q3:
  med = sum(q3)/4

print(med)

"""###Ler um vetor com 20 idades e exibir a maior e menor"""

idades = [15,27,34,23,52,32,54,26,75,21,15,13,41,63,15,16,17,18,20,30]

max(idades)

min(idades)

"""###Inicialize uma lista de 20 números inteiros. Armazene os números pares em uma lista PAR e os números ímpares, em uma lista IMPAR.imprima as listas PAR E IMPAR:"""

jon = [15,7,98,51,61,78,64,84,45,64,6,8,18,1,55,81,31,86,18,68]

impares = []
pares = []

for numb in jon:
  if numb % 2 == 0:
    pares.append(numb)
  else:
    impares.append(numb)

print(impares,pares)

"""



###Faça um programa que receba a temperatura média de cada mês do ano e armazene-as em uma lista em seguida, calcule a média anual das temperaturas e mostre a média calculada juntamente com todas as temperaturas acima da média anual, em que mês elas ocorreram (mostrar os mês por extenso: 1 - janeiro, 2 - Fevereiro,...)."""

meses = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"]

temperatura = []

def jontemp(ano):
    meses = ['Janeiro', 'Fevereiro','Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']
    return meses[ano]

media = lambda x: sum(x)/len(x)

tempano = [] 
for i in range(12):
    temp = float(input('Digite a temperatura do mês:'))
    tempano.append(temp) 

mediano = media(tempano)
print("a media é {:.2f}".format(mediano))
for t in range(len(tempano)):
    if tempano[t] > mediano:
        mes = jontemp(t)
        print('temperatura {0:.2f} maior que a média anual {1:.2f} ocorrida no mês: {2}'.format(tempano[t], mediano, mes))

